#
# Copyright (c) 2021-2022 T-Systems International GmbH (Catena-X Consortium)
#
# See the AUTHORS file(s) distributed with this work for additional
# information regarding authorship.
#
# See the LICENSE file(s) distributed with this work for
# additional information regarding license terms.
#

###########################################################
# Configuration of the AAS Proxy
###########################################################

# Exposed Web Server (Incoming)
server:
  protocol: http
  host: localhost
  port: 4244
openapi:
  dotAASPart2HTTPRESTRegistryAndDiscovery:
    base-path:
# Delegated Web Server (Outgoing)
aasproxy:
  proxyUrl: ${server.protocol}://${server.host}:${server.port}
  registryUrl: http://localhost:4242/
  wrapperUrl: http://localhost:8193/api/service
spring:
  # How to deal with REST representation problems
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: true
