replicaCount: 1

ingress:
  host: prs.local
  className: nginx
  prefix: /mtpdc

prs:
  image:
    repository: prs-api
    tag: "latest"
brokerproxy:
  image:
    repository: broker-proxy
    tag: "latest"

#postgresql:
#  url: "jdbc:postgresql://postgresql:5432/postgres"
#  postgresqlUsername: prs-user
#  postgresqlPassword: <postgres-password>

#eventHubs:
#  namespace: NAMESPACENAME
#  name: HUBNAME
#  sendConnectionString: XXXX
#  receiveConnectionString: XXXX

#applicationInsights:
  #connectionString: <app-insights-connection-string>
