@startuml
'https://plantuml.com/sequence-diagram

autonumber

Kaputt -> KaputtConsumer: http://kaputt-consumer/artifact/prs-id/data/<params>
KaputtConsumer -> PRSProvider: http://prs-provider/artifact/prs-remote-id/data/<params>
PRSProvider -> PRS: http://prs-api/<params>
PRSProvider <-- PRS: {"aspectURL": "http://kaputt-consumer/artifacts/bwn-id/data"}
KaputtConsumer <-- PRSProvider: {"aspectURL": "http://kaputt-consumer/artifacts/bmw-id/data/<params>"}
Kaputt <-- KaputtConsumer: {"aspectURL": "http://kaputt-consumer/artifacts/bmw-id/data/<params>"}
@enduml