@startuml
'https://plantuml.com/sequence-diagram

autonumber

Kaputt ->  KaputtConsumer: Get aspect "http://kaputt-consumer/artifacts/bmw-id/data/<params>"
KaputtConsumer -> BMWProvider: "http://bmw-provider/artifacts/bmw-remote-id/data/<params>"
BMWProvider -> BMWAspectsService: "http://bmw-aspect-service/<params>
BMWProvider <-- BMWAspectsService: AspectData
KaputtConsumer <-- BMWProvider: AspectData
Kaputt <-- KaputtConsumer: AspectData
@enduml