@startuml
'https://plantuml.com/sequence-diagram

autonumber

Kaputt ->  KaputtConsumer: Get aspect "http://kaputt-consumer/artifacts/bmw-id/data/<params>"
KaputtConsumer -> BMWProvider: "http://companyA-provider/artifacts/bmw-remote-id/data/<params>"
CompanyAProvider -> AspectsServiceCompanyA: "http://companyA-aspects-api/<params>
CompanyAProvider <-- AspectsServiceCompanyA: AspectData
KaputtConsumer <-- CompanyAProvider: AspectData
Kaputt <-- KaputtConsumer: AspectData
@enduml