@startuml
'https://plantuml.com/sequence-diagram

autonumber

KaputtService -> KaputtConsumer: GET partsTree
KaputtConsumer -> PRSProvider: GET partsTree
PRSProvider -> PRS: GET partsTree
PRSProvider <-- PRS: {"aspectUrls": ["http://kaputt-consumer/..."] }
KaputtConsumer <-- PRSProvider: {"aspectUrls": ["http://kaputt-consumer/..."] }
KaputtService <-- KaputtConsumer: {"aspectUrls": ["http://kaputt-consumer/..."] }
@enduml