apiVersion: v1
kind: ConfigMap
metadata:
  name: prs-dataspace-config
  labels:
    app.kubernetes.io/name: prs-connector-consumer
data:
  dataspace-partitions.json: {{ .Values.dataspace.partitionsJson | quote }}
  dataspace-deployments.json: {{ .Values.dataspace.deploymentsJson | quote }}