apiVersion: v1
kind: Service
metadata:
  name: prs-connector-consumer
  labels:
    app.kubernetes.io/name: prs-connector-consumer
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9191
      protocol: TCP
  selector:
    app.kubernetes.io/name: prs-connector-consumer
