apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prs-connector-consumer
  labels:
    app.kubernetes.io/name: prs-connector-consumer
    app.kubernetes.io/part-of: prs-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prs-connector-consumer
  serviceName: "prs-connector-consumer"
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "4006"
        prometheus.io/scheme: "http"
        prometheus.io/path: "/metrics"
      labels:
        app.kubernetes.io/name: prs-connector-consumer
    spec:
      containers:
        - name: connector
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8181
              name: http
            - containerPort: 4006
              name: prometheus
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: APPLICATIONINSIGHTS_CONNECTION_STRING
              value: {{ .Values.applicationInsights.connectionString | quote }}
            - name: APPLICATIONINSIGHTS_ROLE_NAME
              value: connector-consumer
