environment="dev"
resource_group_name="catenax-dev001-rg"
image_registry="catenaxdev001acr.azurecr.io"
ingress_host="catenaxdev001akssrv.germanywestcentral.cloudapp.azure.com"
aks_cluster_name="catenax-dev001-aks-services"