global:
  scrape_interval: 10s
  scrape_timeout: 10s

scrape_configs:
  - job_name: services
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          # When target is running in Docker
          - 'prs:4004'
          # When target is running on Host
          - 'host.docker.internal:4004'
        labels:
          service: 'PRS-API'
      - targets:
          - 'broker-proxy:4005'
          - 'host.docker.internal:4005'
        labels:
          service: 'Broker-Proxy'
      - targets:
          - 'consumer:4006'
          - 'host.docker.internal:4007'
        labels:
          service: 'Consumer'
      - targets:
          - 'provider:4006'
          - 'host.docker.internal:4006'
        labels:
          service: 'Provider'
