server:
  port: 8081

spring:
  application:
    name: broker-proxy

kafka:
  topic: catenax.events
  properties:
    bootstrap_servers: localhost:29092

management:
  endpoints:
    web:
      exposure:
        include: health,threaddump,loggers
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState, kafka, diskSpace
      show-details: always
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  server:
    port: 4005

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    root: WARN
    org.springframework: INFO
    net.catenax.brokerproxy: INFO

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
  writer-with-order-by-keys: true

brokerproxy:
  apiUrl: http://localhost:8081
