#
# Copyright (c) 2021 Microsoft (Catena-X Consortium)
#
# See the AUTHORS file(s) distributed with this work for additional
# information regarding authorship.
#
# See the LICENSE file(s) distributed with this work for
# additional information regarding license terms.
#

# K8 Manifest to deploy the shared IAM service based on Keycloak

apiVersion: v1
kind: Service
metadata:
  name: iam
  namespace: iam
  labels:
    app: iam
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: iam
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iam
  namespace: iam
  labels:
    app: iam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iam
  template:
    metadata:
      labels:
        app: iam
    spec:
      containers:
      - name: iam
        image: quay.io/keycloak/keycloak:15.0.2
        env:
        - name: KEYCLOAK_USER
          value: "admin"
        - name: KEYCLOAK_PASSWORD
          value: "admin"
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: DB_VENDOR
          value: "postgres"
        - name: DB_ADDR
          value: "${DB_HOST}.postgres.database.azure.com"
        - name: DB_DATABASE
          value: "iam"
        - name: DB_USER
          value: "${DB_USER}@${DB_HOST}"
        - name: DB_PASSWORD
          value: "${DB_PASSWORD}"
        - name: KEYCLOAK_LOGLEVEL
          value: "INFO"
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        readinessProbe:
          httpGet:
            path: /auth/realms/master
            port: 8080