#
# Copyright (c) 2021 T-Systems International GmbH (Catena-X Consortium)
#
# See the AUTHORS file(s) distributed with this work for additional
# information regarding authorship.
#
# See the LICENSE file(s) distributed with this work for
# additional information regarding license terms.
#

# K8 server deployment, service and ingress 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: semantics2
  namespace: semantics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: semantics2
  template:
    metadata:
      labels:
        app: semantics2
    spec:
      containers:
      - name: semantics2
        image: $CONTAINER_REGISTRY/semantics2:$VERSION
        imagePullPolicy: $IMAGE_PULL_POLICY
        ports:
        env:
          - name: HTTPUSERNAME
            valueFrom:
              secretKeyRef:
                key: http_basic_auth_user
                name: semantics-secret
          - name: HTTPPASSWORD
            valueFrom:
              secretKeyRef:
                key: http_basic_auth_password
                name: semantics-secret
          - name: SPRING_DATASOURCE_DRIVERCLASSNAME
            value: org.postgresql.Driver
          - name: SPRING_DATASOURCE_URL          
            valueFrom:
              secretKeyRef:
                key: database_url
                name: semantics-secret
          - name: SPRING_DATASOURCE_USERNAME          
            valueFrom:
              secretKeyRef:
                key: database_user
                name: semantics-secret
          - name: SPRING_DATASOURCE_PASSWORD          
            valueFrom:
              secretKeyRef:
                key: database_password
                name: semantics-secret
          - name: IDSADAPTER_CONNECTORURL
            value: https://${CATENA_SERVICE_URL}/connectorprovider
          - name: IDSADAPTER_SERVICEURL
            value: https://${CATENA_SERVICE_URL}/semantics2
---
apiVersion: v1
kind: Service
metadata:
  name: semantics2
  namespace: semantics
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 4243
  selector:
    app: semantics2
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: semantics2-ingress
  namespace: semantics
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-service
    acme.cert-manager.io/http01-ingress-class: service
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
spec:
  ingressClassName: service
  tls:
  - hosts:
    - ${CATENA_SERVICE_URL}
    secretName: certificate2-secret
  rules:
  - host: ${CATENA_SERVICE_URL}
    http:
      paths:
      - path: /semantics2(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: semantics2
            port:
              number: 8080