#
# Copyright (c) 2021 T-Systems International GmbH (Catena-X Consortium)
#
# See the AUTHORS file(s) distributed with this work for additional
# information regarding authorship.
#
# See the LICENSE file(s) distributed with this work for
# additional information regarding license terms.
#

# K8 Manifest to expose a certified semantics layer 
# on the service ingress plane
# Use envsubst before applying the descriptor

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  # different name
  name: certificate-service
  namespace: semantics
spec:
  # dedicate secret for the TLS cert
  secretName: certificate-service-secret
  issuerRef:
    # referencing the production issuer
    name: letsencrypt-service
    kind: ClusterIssuer
  dnsNames:
  - ${CATENA_SERVICE_URL}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: semantics-ingress
  namespace: semantics
  annotations:
    kubernetes.io/ingress.class: nginx-service
    cert-manager.io/cluster-issuer: letsencrypt-service
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
spec:
  tls:
  - hosts:
    - ${CATENA_SERVICE_URL}
    secretName: certificate-service-secret
  rules:
  - host: ${CATENA_SERVICE_URL}
    http:
      paths:
      - path: /semantics(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: semantics
            port:
              number: 8080