apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
  name: prs-ingress

spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.prefix }}/(api/.*)
            pathType: Prefix
            backend:
              service:
                name: prs
                port:
                  number: 80
          - path: {{ .Values.ingress.prefix }}/(broker-proxy/.*)
            pathType: Prefix
            backend:
              service:
                name: broker-proxy
                port:
                  number: 80
