apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prs-ingress
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: prs
                port:
                  number: 80
          - path: /broker
            pathType: Prefix
            backend:
              service:
                name: broker-proxy
                port:
                  number: 80