apiVersion: v1
kind: Service
metadata:
  name: prs
  labels:
    app.kubernetes.io/name: prs-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: prs-api
---
apiVersion: v1
kind: Service
metadata:
  name: broker-proxy
  labels:
    app.kubernetes.io/name: broker-proxy
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
  selector:
    app.kubernetes.io/name: broker-proxy
