{{- if .Values.ingress.enabled -}}
{{- $fullName := include "dataspace-connector.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "dataspace-connector.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.ingress.rootPath }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/x-forwarded-prefix: {{ .Values.ingress.rootPath }}
    {{- else }}
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    {{- end }}
    {{- if .Values.ingress.tls.certMgr }}
    cert-manager.io/{{ .Values.ingress.tls.certMgr.kind }}: {{ .Values.ingress.tls.certMgr.issuer }}
    {{- end }}
    nginx.ingress.kubernetes.io/use-regex: "true"
    {{- if .Values.env.config.SERVER_SSL_ENABLED }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.certificate.dnsName }}
    secretName: {{ .Values.ingress.tls.secretName | default (print (include "dataspace-connector.fullname" .) "-certs")  }}
  {{- end }}
  rules:
  - host: {{ .Values.certificate.dnsName }}
    http:
      paths:
        - backend:
            {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
            service:
              name: {{ $fullName }}
              port:
                number: {{ $svcPort }}
            {{- else }}
            serviceName: {{ $fullName }}
            servicePort: {{ $svcPort }}
            {{- end }}
          {{- if .Values.ingress.rootPath }}
          path: "{{ .Values.ingress.rootPath }}(/|$)(.*)"
          {{- else }}
          path: "/(.*)"
          {{- end }}
          {{- if and .Values.ingress.pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
          pathType: {{ .Values.ingress.pathType }}
          {{- end }}
{{- end }}
