version: '3.4'

services:

  provider:
    build:
      context: ..
      target: prs-connector-provider
      args:
        BUILD_TARGET: prs-connector-provider
    ports:
      - 8181:8181
    volumes:
      - ./shared-mount/source:/tmp/copy/source
      - ./shared-mount/dest:/tmp/copy/dest

  consumer:
    build:
      context: ..
      target: prs-connector-consumer
      args:
        BUILD_TARGET: prs-connector-consumer
    ports:
      - 9191:9191
    volumes:
      - ./shared-mount/dest:/tmp/copy/dest
