version: '3.4'

services:

  provider:
    build:
      context: ..
      target: prs-connector-provider
      args:
        BUILD_TARGET: prs-connector-provider
    ports:
      - 8181:8181
    volumes:
      - src-shared-volume:/tmp/copy/source
      - dst-shared-volume:/tmp/copy/dest

  consumer:
    build:
      context: ..
      target: prs-connector-consumer
      args:
        BUILD_TARGET: prs-connector-consumer
    ports:
      - 9191:9191
    volumes:
      - dst-shared-volume:/tmp/copy/dest

  integration-test:
    image: adoptopenjdk:11-jre-hotspot
    command: ci/test.sh
    volumes:
      - src-shared-volume:/tmp/copy/source
      - dst-shared-volume:/tmp/copy/dest
      - ./ci:/ci

volumes:
  src-shared-volume:
    driver_opts:
      type: tmpfs
      device: tmpfs
  dst-shared-volume:
    driver_opts:
      type: tmpfs
      device: tmpfs
