#
# Copyright (c) 2021-2022 T-Systems International GmbH (Catena-X Consortium)
#
# See the AUTHORS file(s) distributed with this work for additional
# information regarding authorship.
#
# See the LICENSE file(s) distributed with this work for
# additional information regarding license terms.
#

###########################################################
# Configuration of the Catena-X Anonymizer Service
###########################################################
application:
  name: catenax-anonymizer
banner:
  location: "classpath:banner.txt"
anonymizer:
  defaultDomain: urn:net.catenax.semantics.anonymizer#