spring:
  application:
    name: parts-relationship-service

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    root: ERROR
    org.springframework: INFO
    net.catenax.prs: INFO

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
