apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prs-connector-provider
  labels:
    app.kubernetes.io/name: prs-connector-provider
    app.kubernetes.io/part-of: prs-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prs-connector-provider
  serviceName: "prs-connector-consumer"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prs-connector-provider
    spec:
      containers:
        - name: connector
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8181
              name: http
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: copy-source
              mountPath: /tmp/copy/source
            - name: copy-dest
              mountPath: /tmp/copy/dest
      volumes:
        - name: copy-source
          configMap:
            name: provider-copy-source
        - name: copy-dest
