apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prs-connector-provider
  labels:
    app.kubernetes.io/name: prs-connector-provider
    app.kubernetes.io/part-of: prs-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prs-connector-provider
  serviceName: "prs-connector-provider"
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "4006"
        prometheus.io/scheme: "http"
        prometheus.io/path: "/metrics"
      labels:
        app.kubernetes.io/name: prs-connector-provider
    spec:
      containers:
        - name: connector
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8181
              name: http
            - containerPort: 4006
              name: prometheus
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: PRS_API_URL
              value: {{ .Values.prs.apiUrl }}
            - name: APPLICATIONINSIGHTS_CONNECTION_STRING
              value: {{ .Values.applicationInsights.connectionString | quote }}
            - name: APPLICATIONINSIGHTS_ROLE_NAME
              value: connector-provider
            - name: edc.vault.clientid
              value: {{ .Values.edc.vault.clientId | quote }}
            - name: edc.vault.tenantid
              value: {{ .Values.edc.vault.tenantId | quote }}
            - name: edc.vault.name
              value: {{ .Values.edc.vault.name | quote }}
            - name: edc.vault.certificate
              value: /certificate/cert.pfx
          volumeMounts:
            - name: certificate
              mountPath: "/certificate/"
              readOnly: true
            - name: copy-source
              mountPath: /tmp/copy/source
            - name: copy-dest
              mountPath: /tmp/copy/dest
      volumes:
        - name: copy-source
        - name: copy-dest
        - name: certificate
          secret:
            secretName: prs-connector-provider-certificate
