spring:
  application:
    name: parts-relationship-service

management:
  endpoints:
    web:
      exposure:
        include: health,threaddump,loggers
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    root: ERROR
    org.springframework: INFO
    net.catenax.prs: INFO

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
