name: Deploy PRS

on:
  push:
    branches:
      - main
    paths:
      - coreservices/partsrelationshipservice/**
      - .github/workflows/partsrelationshipservice-deploy.yml

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: coreservices/partsrelationshipservice
    env:
      TF_VAR_image_registry: catenaxdev001acr.azurecr.io
      # Ingress host to reach the PRS service.
      TF_VAR_ingress_host: catenaxdev001akssrv.germanywestcentral.cloudapp.azure.com
      TF_VAR_aks_cluster_name: catenax-dev001-aks-services
      TF_VAR_resource_group_name: catenax-dev001-rg
      TF_VAR_release_name: prs
      TF_VAR_image_tag: ${{ github.run_id }}
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: "Build and push prs images to ACR"
        run: cd/build_and_push_docker.sh "$TF_VAR_image_registry" "$TF_VAR_image_tag"
      - name: "Deploy to AKS"
        run: |
          # Read terraform outputs (TF_OUT_ variables)
          export ARM_CLIENT_ID=$(echo $AZURE_CREDENTIALS | jq -r .clientId)
          export ARM_CLIENT_SECRET=$(echo $AZURE_CREDENTIALS | jq -r .clientSecret)
          export ARM_TENANT_ID=$(echo $AZURE_CREDENTIALS | jq -r .tenantId)
          export ARM_SUBSCRIPTION_ID=$(az account show --query "id" --output tsv)

          cd terraform
          terraform init
          terraform plan
          terraform apply -auto-approve

        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

  smoketest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: coreservices/partsrelationshipservice

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: |
          mvn --batch-mode --update-snapshots -Dgroups=SmokeTests test