name: PRS Connector sample CI

on:
  pull_request:
    branches:
      - main
    paths:
      - coreservices/partsrelationshipservice/connector/*
      - coreservices/partsrelationshipservice/dev/*
      - coreservices/partsrelationshipservice/Dockerfile
      - coreservices/partsrelationshipservice/docker-compose.yml
      - .github/workflows/partsrelationshipservice-connector.yml

jobs:
  connector_integration_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: coreservices/partsrelationshipservice/connector

    steps:
      - uses: actions/checkout@v2

      - name: Run sample test
        timeout-minutes: 5
        run: |
          echo ${{ PRS_EDC_CONNECTOR_CERTIFICATE }} | base64 --decode > ${edc_vault_certificate}
          ./run-integration-test.sh
        env:
          PRS_EDC_PKG_USERNAME: ${{ secrets.PRS_EDC_PKG_USERNAME }}
          PRS_EDC_PKG_PASSWORD: ${{ secrets.PRS_EDC_PKG_PASSWORD }}
          PRS_EDC_CONNECTOR_CERTIFICATE: ${{ secrets.PRS_EDC_CONNECTOR_CERTIFICATE }}
          edc_vault_certificate: ${HOME}/cert.pfx
          edc_vault_clientid: 0dcdabb0-70db-4ada-8a6b-20cbb6519824
          edc_vault_tenantid: 836f6094-147a-44cc-8064-3dd900228759
          edc_vault_name: cxmtpdc1-dev-consumer
          edc_storage_account_name: cxmtpdc1devconsumer
