name: PRS CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'coreservices/partsrelationshipservice/**'
      - '.github/workflows/partsrelationshipservice.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: coreservices/partsrelationshipservice

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: |
          mvn --batch-mode --update-snapshots -s settings.xml verify
        env:
          PRS_EDC_PKG_USERNAME: ${{ secrets.PRS_EDC_PKG_USERNAME }}
          PRS_EDC_PKG_PASSWORD: ${{ secrets.PRS_EDC_PKG_PASSWORD }}

  build_images:
    strategy:
      matrix:
        image:
          - prs-api
          - broker-proxy
          - prs-connector-provider
          - prs-connector-consumer
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: coreservices/partsrelationshipservice

    steps:
      - uses: actions/checkout@v2

      - name: Build image to make sure Dockerfile is valid
        run: |
          # RUN --mount=type=cache is used in the PRS Dockerfile to cache directories for maven.
          # And the --mount option requires BuildKit.
          DOCKER_BUILDKIT=1 docker build --build-arg PRS_EDC_PKG_USERNAME=${{ secrets.PRS_EDC_PKG_USERNAME }} --build-arg PRS_EDC_PKG_PASSWORD=${{ secrets.PRS_EDC_PKG_PASSWORD }} --build-arg BUILD_TARGET=${{ matrix.image }} --target ${{ matrix.image }} .

  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: coreservices/partsrelationshipservice
    steps:
      - uses: actions/checkout@v2

      - name: Check Terraform files are properly formatted (run "terraform fmt -recursive" to fix)
        run: |
          set -e # safe mode
          terraform fmt -recursive
          git diff --exit-code
