name: PRS Smoke Test

on:
  workflow_run:
    workflows: ["PRS Deploy"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:

jobs:
  smoketest:
    env:
      ENVIRONMENT: DEV
      PRS_DEV_BASEURI: "https://catenaxdev001akssrv.germanywestcentral.cloudapp.azure.com"
      PRS_INT_BASEURI: "https://catenaxintakssrv.germanywestcentral.cloudapp.azure.com"
      KAPUTT_DEV_CONSUMER_ARTIFACT_URI: "https://catenaxdev006akssrv.germanywestcentral.cloudapp.azure.com/kaputt/consumer/api/artifacts/2922a713-61c7-49a1-bbae-114b6a1ad9d8/data"
      KAPUTT_INT_CONSUMER_ARTIFACT_URI: "https://catenaxintakssrv.germanywestcentral.cloudapp.azure.com/kaputt/consumer/api/artifacts/8e46b415-8611-489f-82a4-2e057058adfa/data"
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'}}
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: coreservices/partsrelationshipservice

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Configure environment variables related to the environement to test
        run: |
          echo "PRS_BASEURI=PRS_${ENVIRONMENT}_BASEURI" >> $GITHUB_ENV
          echo "KAPUTT_CONSUMER_ARTIFACT_URI=KAPUTT_${ENVIRONMENT}_CONSUMER_ARTIFACT_URI" >> $GITHUB_ENV
          echo "CONSUMER_USERNAME_SECRET_ID=KAPUTT_${ENVIRONMENT}_CONSUMER_USERNAME" >> $GITHUB_ENV
          echo "CONSUMER_PASSWORD_SECRET_ID=KAPUTT_${ENVIRONMENT}_CONSUMER_PASSWORD" >> $GITHUB_ENV

      - name: Run PRS smoke tests
        run: mvn --batch-mode --update-snapshots -Dgroups=SmokeTests test -DbaseURI=${{ env.PRS_DEV_BASEURI }}

      - name: Run PRS Smoke tests against Kaputt connector
        run: mvn --batch-mode --update-snapshots -Dgroups=SmokeTests test -DbaseURI=KAPUTT_DEV_CONSUMER_ARTIFACT_URI -DuserName=${{ secrets.[env.CONSUMER_USERNAME_SECRET_ID] }} -Dpassword=${{ secrets.[env.CONSUMER_PASSWORD_SECRET_ID] }}
