name: PRS Deploy

on:
  push:
    branches:
      - main
      - feature/CAX-1-MTPDC@75-system-test
    paths:
      - coreservices/partsrelationshipservice/**
      - .github/workflows/partsrelationshipservice-deploy.yml

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy PRS to'
        required: true
        default: 'dev'

jobs:
  configure:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: coreservices/partsrelationshipservice
    env:
      # Default environment to deploy (overridden when deploying manually)
      ENVIRONMENT_TO_DEPLOY: dev
    steps:
      - uses: actions/checkout@v2
      - name: "Configure environment to deploy (manual deployment only)"
        if: ${{ github.event_name == 'workflow_dispatch'}}
        run: |
          echo "ENVIRONMENT_TO_DEPLOY=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
      - id: get-dataspace-partitions
        run: |
          set -euo pipefail # safe mode
          dataspace_partitions=$(jq -c .partitions cd/dataspace-partitions.json)
          echo "::set-output name=dataspace_partitions::$dataspace_partitions"
    outputs:
      dataspace_partitions: ${{ steps.get-dataspace-partitions.outputs.dataspace_partitions }}
      environment: ${{ env.ENVIRONMENT_TO_DEPLOY }}
      image_tag: 1406887097

  deploy:
    needs:
    - configure
    strategy:
      # avoid stopping concurrent jobs (leaving Terraform state potentially corrupted/leased) on job failure
      fail-fast: false
      matrix:
        partition: ${{ fromJson(needs.configure.outputs.dataspace_partitions) }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: coreservices/partsrelationshipservice
    env:
      ENVIRONMENT: ${{ needs.configure.outputs.environment }}
      # Variables prefixed with TF_VAR_ are automatically picked up as Terraform inputs
      TF_VAR_dataspace_partition: ${{ matrix.partition.key }}
      TF_VAR_image_tag: ${{ needs.configure.outputs.image_tag }}
    steps:
      - run: env
      - run: echo $GITHUB_JOB
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Run Terraform, deploying infrastructure to Azure and application to AKS"
        run: |
          set -euo pipefail # safe mode

          # Settings and credential for Terraform azurerm provider
          export ARM_CLIENT_ID=$(echo $AZURE_CREDENTIALS | jq -r .clientId)
          export ARM_CLIENT_SECRET=$(echo $AZURE_CREDENTIALS | jq -r .clientSecret)
          export ARM_TENANT_ID=$(echo $AZURE_CREDENTIALS | jq -r .tenantId)
          export ARM_SUBSCRIPTION_ID=$(az account show --query "id" --output tsv)

          pushd terraform
            terraform init -backend-config=key=mtpdc.$ENVIRONMENT.${{ matrix.partition.key }}.tfstate
            terraform apply --var-file "../cd/environments/$ENVIRONMENT.tfvars" -var dataspace_partition=${{ matrix.partition.key }} -auto-approve
            terraform output -json > ../terraform-outputs.json

        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Cache maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run smoke tests
        run: |
          set -euo pipefail # safe mode
          api_url=$(jq -r .api_url.value terraform-outputs.json)
          mvn --batch-mode --update-snapshots -Dgroups=SmokeTests test -DbaseURI=$api_url

      - name: "Load test data"
        run: |
          set -euo pipefail # safe mode
          export POSTGRES_USER=$(jq -r .prs_db_administrator_username.value terraform-outputs.json)
          export POSTGRES_PASSWORD=$(jq -r .prs_db_administrator_login_password.value terraform-outputs.json)
          export POSTGRES_HOST=$(jq -r .prs_db_fqdn.value terraform-outputs.json)
          export POSTGRES_DB=$(jq -r .prs_db_name.value terraform-outputs.json)
          pushd cd/test-data
            ./load-test-data.sh

      - id: set-output
        run: |
          set -euo pipefail # safe mode
          api_url=$(jq -r .api_url.value terraform-outputs.json)
          echo '::set-output name=api_url_${{ matrix.partition.key }}::$api_url'

  system_test:
    needs:
    - deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: coreservices/partsrelationshipservice
    steps:
      - uses: actions/checkout@v2

      - env:
          NEEDS: ${{ toJSON(needs) }}
        run: echo "$NEEDS"

      - name: "Run system tests"
        run: |
          set -euo pipefail # safe mode
          api_url=${{ needs.deploy.outputs.api_url_bmw }}
          mvn --batch-mode --update-snapshots -Dgroups=SystemTests test -DbaseURI=$api_url -Denvironment=$ENVIRONMENT
