name: Deploy

on:
  push:
    branches:
      - main
      - feature/CAX-1-PRS@132-prs-terraform-helm
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: coreservices/partsrelationshipservice
    env:
      TF_VAR_image_registry: catenaxdev001acr.azurecr.io
      # Ingress host to reach the PRS and broker-proxy service.
      INGRESS_HOST: prsdev.d5a2b853cc864506ac03.germanywestcentral.aksapp.io
      TF_VAR_aks_cluster_name: catenax-dev001-aks-services
      TF_VAR_resource_group_name: catenax-dev001-rg
      TF_VAR_release_name: prs
      TF_VAR_image_tag: ${{ github.run_id }}
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: "Build and push prs and broker-proxy images to ACR"
        run: cd/build_and_push_docker.sh "$TF_VAR_image_registry" "$TF_VAR_image_tag"
      - name: "Deploy to AKS"
        run: |
          # Read terraform outputs (TF_OUT_ variables)
          export ARM_CLIENT_ID=$(echo $AZURE_CREDENTIALS | jq -r .clientId)
          export ARM_CLIENT_SECRET=$(echo $AZURE_CREDENTIALS | jq -r .clientSecret)
          export ARM_TENANT_ID=$(echo $AZURE_CREDENTIALS | jq -r .tenantId)
          export ARM_SUBSCRIPTION_ID=$(az account show --query "id" --output tsv)

          cd terraform
          terraform init
          terraform plan
          terraform apply -var resource_group_name=$TF_VAR_resource_group_name \
          -var aks_cluster_name=$TF_VAR_aks_cluster_name \
          -var image_registry=$TF_VAR_image_registry \
          -var image_tag=$TF_VAR_image_tag \
          -var release_name=$TF_VAR_release_name \
          -var ingress_host=$INGRESS_HOST
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

