name: PRS Deploy

on:
  push:
    branches:
      - feature/A1MTDC@148-edc-system-test

jobs:

  system_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: coreservices/partsrelationshipservice
    env:
      ENVIRONMENT: dev
    steps:
      - uses: actions/checkout@v2

      - run: |
        . cd/environments/dev.sh
        echo "TF_VAR_aks_cluster_name=$TF_VAR_aks_cluster_name" >> $GITHUB_ENV
        echo "TF_VAR_resource_group_name=$TF_VAR_resource_group_name" >> $GITHUB_ENV

      # Set the target Azure Kubernetes Service (AKS) cluster. 
      - uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: ${{ env.TF_VAR_aks_cluster_name }}
          resource-group: ${{ env.TF_VAR_resource_group_name }}

      - run: kubectl logs -n prs-connectors prs-connector-provider-0

      - name: Cache maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: systemtest-${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: "Run system tests"
        run: |
          set -euo pipefail # safe mode
          mvn --batch-mode --update-snapshots -s settings.xml -Dgroups=SystemTests test -Denvironment=$ENVIRONMENT
        env:
          PRS_EDC_PKG_USERNAME: ${{ secrets.PRS_EDC_PKG_USERNAME }}
          PRS_EDC_PKG_PASSWORD: ${{ secrets.PRS_EDC_PKG_PASSWORD }}
