name: Deploy

on:
  push:
    branches:
      - main
      - feature/CAX-1-PRS@134-prs-terraform-helm
  workflow_dispatch:
    inputs:
      imageRegistry:
        description: 'Image registry'
        required: true
        default: catenaxdev001acr.azurecr.io
      ingressHost:
        description: 'Ingress host to reach the PRS service'
        required: true
        default: prsdev.d5a2b853cc864506ac03.germanywestcentral.aksapp.io
      aksClusterName:
        description: 'AKS cluster name'
        required: true
        default: catenax-dev001-aks-services
      resourceGroupName:
        description: 'Resource group name where the resources are created'
        required: true
        default: catenax-dev001-rg
      releaseName:
        description: 'PRS release name'
        required: true
        default: prs

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: coreservices/partsrelationshipservice
    env:
      TF_VAR_image_registry: $INPUT_IMAGE_REGISTRY
      # Ingress host to reach the PRS service.
      TF_VAR_ingress_host: $INPUT_INGRESS_HOST
      TF_VAR_aks_cluster_name: $INPUT_AKS_CLUSTER_NAME
      TF_VAR_resource_group_name: $INPUT_RESOURCE_GROUP_NAME
      TF_VAR_release_name: $INPUT_RELEASE_NAME
      TF_VAR_image_tag: ${{ github.run_id }}
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: "Build and push prs images to ACR"
        run: cd/build_and_push_docker.sh "$TF_VAR_image_registry" "$TF_VAR_image_tag"
      - name: "Deploy to AKS"
        run: |
          # Read terraform outputs (TF_OUT_ variables)
          export ARM_CLIENT_ID=$(echo $AZURE_CREDENTIALS | jq -r .clientId)
          export ARM_CLIENT_SECRET=$(echo $AZURE_CREDENTIALS | jq -r .clientSecret)
          export ARM_TENANT_ID=$(echo $AZURE_CREDENTIALS | jq -r .tenantId)
          export ARM_SUBSCRIPTION_ID=$(az account show --query "id" --output tsv)

          cd terraform
          terraform init
          terraform plan
          terraform apply -auto-approve

        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

