name: PRS Load Test Data

on:
  push:
    branches:
      - feature/CAX-1-MTPDC@78-system-test
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to load test data to'
        required: true
        default: 'dev'

jobs:
  loaddata:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: coreservices/partsrelationshipservice
    steps:
      - uses: actions/checkout@v2

      - name: "Run system tests"
        run: |
          set -euo pipefail # safe mode
          set -x # verbose (UNSAFE)
          source cd/environments/${{ github.event.inputs.environment }}.tfvars
          mvn --batch-mode --update-snapshots -Dgroups=SystemTests test -DbaseURI=https://$ingress_host -Denvironment=$ENVIRONMENT
