name: PRS Deploy

on:
  push:
    branches:
      - main
    paths:
      - coreservices/partsrelationshipservice/**
      - .github/workflows/partsrelationshipservice-deploy.yml

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy PCR to'
        required: true
        default: 'dev'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: coreservices/partsrelationshipservice
    env:
      # Variables prefixed with TF_VAR_ are automatically picked up as Terraform inputs
      TF_VAR_image_tag: ${{ github.run_id }}
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: "Build and push PRS images to ACR"
        run: cd/build_and_push_docker.sh "$TF_VAR_image_registry" "$TF_VAR_image_tag"
      - name: "Run Terraform, deploying infrastructure to Azure and application to AKS"
        run: |
          set -euo pipefail # safe mode

          # Settings and credential for Terraform azurerm provider
          export ARM_CLIENT_ID=$(echo $AZURE_CREDENTIALS | jq -r .clientId)
          export ARM_CLIENT_SECRET=$(echo $AZURE_CREDENTIALS | jq -r .clientSecret)
          export ARM_TENANT_ID=$(echo $AZURE_CREDENTIALS | jq -r .tenantId)
          export ARM_SUBSCRIPTION_ID=$(az account show --query "id" --output tsv)

          TERRAFORM_DEPLOY_VAR_FILE=environments/${{ github.event.inputs.environment }}.tfvars
          TERRAFORM_STATE_KEY=prs.prs.${{ github.event.inputs.environment }}.terraform.tfstate

          pushd terraform
            terraform init -backend-config=key=${TERRAFORM_STATE_KEY}
            terraform apply --var-file ${DEPLOY_VAR_FILE} -auto-approve

        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
