#
# Copyright (c) 2021 T-Systems International GmbH (Catena-X Consortium)
#
# See the AUTHORS file(s) distributed with this work for additional
# information regarding authorship.
#
# See the LICENSE file(s) distributed with this work for
# additional information regarding license terms.
#

#####################################################
# Github Workflow for continuous terraform deployment
#####################################################

name: Terraform Deploy
on: 
  push:
    paths:
      - 'infrastructure/terraform/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    #
    # TODO choose workspace depending on the current branch/feature prefix
    #
    env:
      WORKSPACE: dev042
    steps:

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.10

    - name: Checkout
      uses: actions/checkout@v2

    - name: Terraform Init
      working-directory: ./infrastructure/terraform
      run: | 
          terraform init

#    - name: Download old tfstate
#      run: |
#        az storage blob download --name dev042.terraform.tfstate --container-name tfstate --account-name catenaxterraformstate --auth-mode login --file .terraform/terraform.tfstate

    - name: Terraform Save Plan
      working-directory: ./infrastructure/terraform
      run: |
        terraform plan --var-file=./infrastructure/terraform/environments/${WORKSPACE}.tfvars -out ./infrastructure/terraform/.terraform/terraform.plan

    - name: Upload Plan
      working-directory: ./infrastructure/terraform
      run: |
        az storage blob upload --name ${WORKSPACE}.terraform.plan --container-name tfstate --account-name catenaxterraformstate --auth-mode login --file ./infrastructure/terraform/.terraform/terraform.plan

    - name: Terraform Auto-Apply
      working-directory: ./infrastructure/terraform
      run: |
        terraform apply -auto-approve --var-file=./infrastructure/terraform/environments/${WORKSPACE}.tfvars ./infrastructure/terraform/.terraform/terraform.plan

    - name: Upload State
      working-directory: ./infrastructure/terraform
      run: |
        az storage blob upload --name ${WORKSPACE}.terraform.plan --container-name tfstate --account-name catenaxterraformstate --auth-mode login --file ./infrastructure/terraform/.terraform/terraform.tfstate