#
# Copyright (c) 2021 T-Systems International GmbH (Catena-X Consortium)
#
# See the AUTHORS file(s) distributed with this work for additional
# information regarding authorship.
#
# See the LICENSE file(s) distributed with this work for
# additional information regarding license terms.
#

#####################################################
# Github Workflow for continuous terraform deployment
#####################################################

name: Terraform Deploy

# Should trigger upon pushs to the terraform related folders

on: 
  push:
    paths:
      - 'infrastructure/terraform/**'
      - '.github/workflows/terraform.yml'

# Consists of two jobs, the first determines the environment
# and the second one (doing the real work) only triggers
# if such an environment can be detected (else the workflow is
# green without doing something)

jobs:

  # First job to determine the environment
  environment:
    name: Determine Target Environment
    runs-on: ubuntu-latest
    outputs:
      workspace: ${{ steps.setvars.outputs.workspace }}

    steps:
      - name: Set variables
        id: setvars
        run: |
          if [[ "${{github.repository}}" == eclipse/tractusx ]]; then
             if [[ "${{github.ref}}" == refs/heads/main ]]; then
                echo "Determined PRODUCTION"
                echo "::set-output name=workspace::prod"
             else
                echo "Unsupported Environment on ECLIPSE. Leaving Workspace empty."
             fi
          else 
            if [[ "${{github.repository}}" == catenax/tractusx ]]; then
              if [[ "${{github.ref}}" == refs/heads/main ]]; then
                echo "Determined INTEGRATION"
                echo "::set-output name=workspace::int"
              elif [[ "${{github.ref}}" = refs/heads/feature/CAX-1-semantics || "${{github.ref}}" = refs/heads/feature/CAX-1-semantics@CXMVP-63-semantic-architecture ]]; then
                  echo "Determined SEMANTICS"
                  echo "::set-output name=workspace::dev042"
              else 
                  echo "Unsupported Branch on CATENAX. Leaving Workspace empty."
              fi
            else
                echo "Unsupported Environment/Repository. Leaving Workspace empty."
            fi
          fi

  # Second job to do the real terraform work
  terraform:
    name: Terraform Target Environment
    runs-on: ubuntu-latest
    # rely on the first job
    needs: environment
    # rely on successful detection of the workspace, ignore if empty
    if: ${{needs.environment.outputs.workspace}}
    env:
      WORKSPACE: ${{needs.environment.outputs.workspace}}
    steps:

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.10

    - name: Checkout
      uses: actions/checkout@v2

    - name: Terraform Init
      working-directory: ./infrastructure/terraform
      run: | 
          terraform init

#    - name: Download old tfstate
#      run: |
#        az storage blob download --name dev042.terraform.tfstate --container-name tfstate --account-name catenaxterraformstate --auth-mode login --file .terraform/terraform.tfstate

    - name: Download SSH Keys
<<<<<<< HEAD
      env:

=======
      working-directory: ./infrastructure/terraform
>>>>>>> 6f383c2 (https://jira.catena-x.net/browse/CATART0PO6-5 Download ssh key to correct working dir.)
      run: |
        az storage blob download --name ${{needs.environment.outputs.workspace}}.ssh.pub --container-name tfstate --account-name catenaxterraformstate --auth-mode key --account-key ${{secrets.TFSTATE_STORAGEACCOUNT_KEY}} --file ssh.pub

    - name: Terraform Save Plan
      working-directory: ./infrastructure/terraform
      run: |
        terraform plan --var-file=environments/${{needs.environment.outputs.workspace}}.tfvars -var azure_subscription_id=${{secrets.AZURE_SUBSCRIPTION_ID}} -var azure_client_id=${{secrets.AZURE_AD_CLIENT_ID}} -var azure_client_secret=${{secrets.AZURE_AD_CLIENT_SECRET}} -var azure_tenant_id=${{secrets.AZURE_AD_TENANT_ID}} -var public_ssh_key=./ssh.pub -out .terraform/terraform${GITHUB_SHA}.plan

    - name: Upload Plan
      working-directory: ./infrastructure/terraform
      run: |
        az storage blob upload --name ${{needs.environment.outputs.workspace}}terraform${GITHUB_SHA}.plan --container-name tfstate --account-name catenaxterraformstate --auth-mode key --account-key ${{secrets.TFSTATE_STORAGEACCOUNT_KEY}} --file .terraform/terraformterraform${GITHUB_SHA}.plan

    #- name: Terraform Auto-Apply
    #  working-directory: ./infrastructure/terraform
    #  run: |
    #    terraform apply -auto-approve --var-file=environments/${WORKSPACE}.tfvars .terraform/terraform.plan

    #- name: Upload State
    #  working-directory: ./infrastructure/terraform
    #  run: |
    #    az storage blob upload --name ${WORKSPACE}.terraform.plan --container-name tfstate --account-name catenaxterraformstate --auth-mode login --file .terraform/terraform.tfstate